database:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/registerSystemProject?useSSL=false&createDatabaseIfNotExist=true
  username: root
  password: user

package: 
  packageToScan: com.registersystem.domain